#!/usr/bin/env python3

# Load modules from $JUJU_CHARM_DIR/lib
import sys

sys.path.append("lib")

from charms.layer import basic

basic.bootstrap_charm_deps()
basic.init_config_states()


from charms import reactive


reactive.set_state("storpool-block-charm.lxd")
reactive.main()
